### ISSUE TITLE
Adjust timestamps

### ISSUE THREAD

**Issue by zhangjoe99** [zhangjoe99/CustomWhisper#6]
Currently, whispertest.ipynb takes an audio file and runs it through openai's whisper model. The model has been modified to include the timestamps of each individual word and the word confidence score.

The last cell of whispertest.ipynb shows the timestamps being off by about 0.5 seconds for the first word of the audio.

Goal:
1. Fix the start timestamp to be as accurate as possible (by modifying stable_whisper.py or alternative)
2. Add end timestamp to each word (ex. word1 from timestamp 0.5 to 0.7 seconds)

**Comment by davisv7** [comment]
Are the timestamps always off with a positive delay? 
Maybe the whisper is taking the midpoint between the starting timestamp and the ending timestamp.

**Comment by zhangjoe99** [comment]
Hmm, maybe I'm not sure, didn't check for that

**Comment by Khaliid-oh** [comment]
Can I have a go at this?

**Comment by zhangjoe99** [comment]
> Can I have a go at this?

Ahh, sry we try to give the person who claimed the bounty first to have a go at it.

**Comment by Khaliid-oh** [comment]
Alright
