### ISSUE TITLE
Improve Neo4j Query

### ISSUE THREAD

**Issue by zhangjoe99** [zhangjoe99/CustomWhisper#9]
Currently, the search endpoint neo4j query is split into multiple parts. We would like to improve this by combining all parts into one query while keeping the same returns.
The graph consists of multiple node types (**Topic**, **Content**, **Episode**, **Guest**, **Show**, **Host**) connected to each other such that:
**Topic** -- **Content** -- **Episode** -- **Show** (There will always be connections in this sequence)
**Guest** -- **Episode** (There is not always a Guest node connected to an Episode node)
**Host** -- **Episode** (There is not always a Host node connected to an Episode node)

The input is a list of topics. Example:
$search_list = ['lightning node', 'jones']
$skip = 0
$limit = 100

_**First query**_
The first query finds all the **Topic** or **Guest** nodes that match any topic in the input (Ex. 'Lightning' and 'Bobby Jones' both match the input, case insensitive) and returns all the connected **Content, Episode, Show**, and **Guest** nodes that match.
```
MATCH (t:Topic)-[r]-(n:Content)--(e:Episode)--(s:Show) OPTIONAL MATCH (e)--(g:Guest) OPTIONAL MATCH (e)--(h:Host)
WITH t, r, n, e, s, g, h WHERE toLower(t.topic) IN $search_list
OR toLower(g.guest) IN $search_list
OR any(word IN $search_list WHERE t.topic CONTAINS word OR g.guest CONTAINS word)
RETURN n, e, s, collect(h) as hosts, collect(g) as g, sum(r.weight) as weight, false as keyword ORDER BY weight DESC SKIP $skip LIMIT $limit
```

_**Second query**_
The second query is a full text search on 'text_full_index'. using the db.index.fulltext.queryNodes call. 'keyword' being returned is true if it is matched in this query. (Example: If a **Content** node n is matched in the first query but not matched in the second query, keyword is false. If it is matched in both queries, keyword is true. And of course if it is only matched in the second query, keyword is true). For the 'weight' the first query takes priority (If node n is matched in both queries, 'weight' should be sum(r.weight))
```
CALL db.index.fulltext.queryNodes('text_full_index', $search + '~') YIELD node, score
WHERE score > $search_threshold
MATCH (node)--(e:Episode)--(s:Show) OPTIONAL MATCH (e)--(g:Guest) OPTIONAL MATCH (e)--(h:Host)
RETURN node as n, e, s, collect(h) as hosts, collect(g) as g, 0 as weight, true as keyword, SKIP $skip LIMIT $limit
```

_**Goal**_
The goal is to combine these two queries into a single one as specified above, in order of 'weight' with limit $limit.

**Comment by zhangjoe99** [comment]
[Raj725](https://github.com/Raj725)
Hey just wondering if you would like to try and tackle this. Let me know and I'll assign you. No worries if not

**Comment by Raj725** [comment]
@zhangjoe99 I would like to try, Please assign it to me.

**Comment by Raj725** [comment]
@zhangjoe99 Can you share which neo4j version you are using? 
Is it Neo4j 4.X or greater than it?

**Comment by Raj725** [comment]
Also, do you have the `apoc` plugin installed?

**Comment by Raj725** [comment]
@zhangjoe99 Please check if this works.

```
CALL {
	MATCH (t:Topic)-[r]-(n:Content)--(e:Episode)--(s:Show) 
	OPTIONAL MATCH (e)--(g:Guest) 
	OPTIONAL MATCH (e)--(h:Host)
	WHERE toLower(t.topic) IN $search_list
		OR toLower(g.guest) IN $search_list
		OR any(word IN $search_list WHERE t.topic CONTAINS word 
		OR g.guest CONTAINS word)
	RETURN n, e, s, h AS host, g, r.weight AS weight, false AS keyword 

	UNION ALL

	CALL db.index.fulltext.queryNodes('text_full_index', $search + '~') YIELD node, score
	WHERE score > $search_threshold
	MATCH (node)--(e:Episode)--(s:Show) 
	OPTIONAL MATCH (e)--(g:Guest) 
	OPTIONAL MATCH (e)--(h:Host)
	RETURN node AS n, e, s, h AS host, g, 0 AS weight, true AS keyword 
}

WITH n, e, s, collect(host) AS hosts, collect(g) AS g, sum(weight) AS weight, collect(keyword) AS keywords
RETURN n, e, s, hosts, g, weight, any(x IN keywords WHERE x=true) AS keyword
ORDER BY weight DESC 
SKIP $skip 
LIMIT $limit
```

**Comment by zhangjoe99** [comment]
@Raj725 Hmm, the query doesn't seem to be returning as expected. The first result returned is not connected to the topic searched. I have emailed you with access details to the graph

**Comment by Raj725** [comment]
@zhangjoe99 Sorry for the inconvenience, I missed one `WITH` line while formatting the query. 

Please check this:

```
CALL {

	MATCH (t:Topic)-[r]-(n:Content)--(e:Episode)--(s:Show) 
	OPTIONAL MATCH (e)--(g:Guest) 
	OPTIONAL MATCH (e)--(h:Host)
	WITH t, r, n, e, s, g, h
	WHERE toLower(t.topic) IN $search_list
		OR toLower(g.guest) IN $search_list
		OR any(word IN $search_list WHERE t.topic CONTAINS word 
		OR g.guest CONTAINS word)
	RETURN n, e, s, h AS host, g, r.weight AS weight, false AS keyword 

	UNION ALL

	CALL db.index.fulltext.queryNodes('text_full_index', $search + '~') YIELD node, score
	WHERE score > $search_threshold
	MATCH (node)--(e:Episode)--(s:Show) 
	OPTIONAL MATCH (e)--(g:Guest) 
	OPTIONAL MATCH (e)--(h:Host)
	RETURN node AS n, e, s, h AS host, g, 0 AS weight, true AS keyword 
}

WITH n, e, s, host, g, weight, keyword
WITH n, e, s, collect(host) AS hosts, collect(g) AS g, sum(weight) AS weight, collect(keyword) AS keywords
RETURN n, e, s, hosts, g, weight, any(x IN keywords WHERE x=true) AS keyword
ORDER BY weight DESC 
SKIP $skip 
LIMIT $limit

```

**Comment by zhangjoe99** [comment]
Ok looks good!

**Comment by Raj725** [comment]
Thank you for the opportunity. Please reach out to me if you have any Neo4j tasks in the future. 
Please invite me to Sphinx when the new user registration starts working.
Thank you :)
